[workspace]
members = [
  "smartcard-apdu",
  "smartcard-core",
  "smartcard-pcsc",
  "smartcard-piv",
  "smartcard-worker",
  "smartcard-pkcs11",
  "smartcard-cli",
]
default-members = ["smartcard-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
pcsc = "2.9"
rsa = "0.9"
sha2 = { version = "0.10", features = ["oid"] }
smartcard-apdu = { path = "smartcard-apdu" }
smartcard-core = { path = "smartcard-core" }
smartcard-pcsc = { path = "smartcard-pcsc" }
smartcard-piv = { path = "smartcard-piv" }
smartcard-worker = { path = "smartcard-worker" }
smartcard-pkcs11 = { path = "smartcard-pkcs11" }
x509-parser = "0.18"
